### ISSUE TITLE
Tiling artefacts

### ISSUE THREAD

**Issue by Atlis** [Piraxus/Skybolt#16]
Hi Matthew,

I get these tiling artifacts in commit b4651bbe0e684c8dab7669686104297ee7240aa1. Is this expected?
![Untitled](https://user-images.githubusercontent.com/6990801/173188247-371ed12a-809f-40db-b151-396c0d2610a2.png)

**Comment by matthew-reid** [comment]
It's not expected, I haven't seen that before. Do you see the lines on on every tile or only some? Can you please post a closeup screenshot of the artifacts with the camera zoomed in right to the surface?

**Comment by Atlis** [comment]
It's on every tiles.
Here is a closeup:
![Untitled](https://user-images.githubusercontent.com/6990801/173233520-7b671c43-70d0-4966-b3a9-637175a4e0de.png)

**Comment by Atlis** [comment]
By the way I get these artefacts in the clouds too. It seems to be related to clouds crossing with the terrain. Same here, is this expected?
![Untitled](https://user-images.githubusercontent.com/6990801/173233738-2fa909ff-cc7a-4c42-823e-e2b887aa8de8.png)
![Untitled2](https://user-images.githubusercontent.com/6990801/173234056-1491d089-1ff4-4bbb-aeb5-1609ae3fc06c.png)

**Comment by Atlis** [comment]
An extreme case (happened only once):
![Untitled3](https://user-images.githubusercontent.com/6990801/173249178-3bb82ab4-9f54-4e52-8ccd-4749d67f70a7.png)

**Comment by matthew-reid** [comment]
I suspect your build of OSG has a bad default texture clamping mode. In 2018 OSG switched from GL_CLAMP to GL_CLAMP_EDGE as the default. If your build is 3.6.5 it should use GL_CLAMP_EDGE, however maybe whoever built it reverted the clamping mode switch for some reason. GL_CLAMP is an ancient OpenGL features which is deprecated and should not be used. It causes textures to read a border color at edges instead of the texture value.

I was able to replicate the effect by switching my build to GL_CLAMP:
![GL_CLAMP_bug](https://user-images.githubusercontent.com/2742081/173281248-60e70214-9144-43af-a1f2-99742db82763.jpg)

I've pushed a [commit ](https://github.com/Piraxus/Skybolt/commit/96bfe7b0f4b9ccf8e245920f7238b6a5abbbd66c) to master which explicitly overrides the OSG defaults to GL_CLAMP_EDGE. Please give it a try.

I also pushed a [commit ](https://github.com/Piraxus/Skybolt/commit/64fefc02515c14f4b17bdd3b6c842d0d0d74f3d0) which fixes the cloud banding artifacts near terrain. That problem is mostly solved, however the cloud/terrain interactions still look wrong because the clouds to not take the scene depth information into account. I want to improve that in the future.

**Comment by Atlis** [comment]
I recompiled. Everything looks fine now. Problem solved. Thank you very much Matthew. 💯
