### ISSUE TITLE
SkyboltExamples MinimalApp error

### ISSUE THREAD

**Issue by lminkov** [Piraxus/Skybolt#3]
Hello,
I tried to run MinimalApp and got the following error:  Could not locate file: Tiles/Earth/Features

Here is the output:

C:\Users\Leonid.Minkov\Documents\proj\skybolt\bld-17\bin\Debug>minimalapp --sett
ingsFile Settings.json
[2021-04-11 21:42:03.263782] [0x00001ba4] [info]    Reading settings file '"Sett
ings.json"'
[2021-04-11 21:42:03.277783] [0x00001ba4] [info]    4 CPU cores detected. Creati
ng 3 background threads.
[2021-04-11 21:42:03.280783] [0x00001ba4] [info]    Registered asset module: Cor
e
[2021-04-11 21:42:03.280783] [0x00001ba4] [info]    Registered asset module: Sha
ders
[2021-04-11 21:42:12.933335] [0x00001ba4] [error]   Could not locate file: Tiles
/Earth/Features

I registered at mapbox.com and got a key.

Here is the content of the settings file:
{
    "tileApiKeys": {
        
        "mapbox": "pk.eyJ1IjoibG1pbmtvdiIsImEiOiJja25ja2MxZHMw....."
    }
}

I downloaded 'Core_1_0_0' folder, and copied "Core" folder from it into 'C:\Users\Leonid.Minkov\Documents\proj\skybolt\bld-17\bin\Debug\Assets' but 'Core\Tiles\Earth' folder does not have 'Features' folder.

Please help. Thank you.

**Comment by matthew-reid** [comment]
I investigated and found the problem is caused by this line in the Assets/Core/Entities/PlanetEarth.json entity:
```
			"features": {
				"directory": "Tiles/Earth/Features"
			},
```
It refers to feature tiles in the directory, but the directory does not exist unless you have the Seattle asset package installed. I will do some work to make the dependency optional. In the meantime you can work-around the issue by either removing the above line from the PlanetEarth entity, or [downloading ](https://piraxus.com/downloads/assetpackages.html) and adding the Seattle package to your Assets folder.

**Comment by lminkov** [comment]
Thank you. It is working now....
