### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by BinBinMind** [Piraxus/Skybolt#6]
I got all tests passed and got a mapbox data key, but i got a black screen
![image](https://user-images.githubusercontent.com/4458014/144166260-0b630db7-4966-4585-9bc7-3f5230e07c3f.png)

**Comment by matthew-reid** [comment]
That's strange. You should see a render of planet earth viewed from space.

You may have an OpenGL or OpenSceneGraph issue. Which version of OpenSceneGraph are you using, and what graphics hardware are you running on?

**Comment by BinBinMind** [comment]
My OpenScenGraph version is 3.6.4，and my graphic card is RTX2080ti. I guess Maybe  something wrong with my gis data. I will check it out again.

**Comment by matthew-reid** [comment]
Skybolt requires OpenSceneGraph 3.6.5 or later. This is supposed to be enforced by CMake find_package, see https://github.com/Piraxus/Skybolt/blob/master/src/Skybolt/SkyboltVis/CMakeLists.txt#L11

I don't think the problem is your terrain data because you should see the globe even if no tiles were loaded.

**Comment by BinBinMind** [comment]
I will try the newer version of OpenSceneGraph and re-check my dependency issues, thank you so much!
